version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: blog-sqlserver
    environment:
      - SA_PASSWORD=YourStrongPassword!  # Cambia esta contraseña
      - ACCEPT_EULA=Y
    ports:
      - "1444:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: